// ─── providers.js ─────────────────────────────────────────────────────────────
// Definición de proveedores LLM y sus modelos sugeridos.

export const PROVIDERS = [
        { id: 'google',      label: 'Google Gemini',  desc: 'Gemini 1.5 Pro / Flash' },
    { id: 'cohere',      label: 'Cohere',         desc: 'Command R+, Command R' },
    { id: 'grok',        label: 'xAI (Grok)',     desc: 'Grok-1, Grok-2' },
    { id: 'perplexity',  label: 'Perplexity',     desc: 'Sonar models with search' },
    { id: 'together',    label: 'Together AI',    desc: 'Llama, Qwen, Mistral gateway' },
    { id: 'cerebras',    label: 'Cerebras',       desc: 'Fastest Llama-3 inference' },
    { id: 'qwen',        label: 'Qwen (Alibaba)', desc: 'Qwen-2.5-72B, Qwen-VL' },
    { id: 'glm',         label: 'Zhipu (GLM)',    desc: 'GLM-4' },
    { id: 'groq',        label: 'Groq',           desc: 'Ultra-fast inference (LPU)' },
    { id: 'openai',      label: 'OpenAI',          desc: 'GPT-4o, o1, o3…' },
    { id: 'anthropic',   label: 'Anthropic',       desc: 'Claude Sonnet / Opus' },
    { id: 'openrouter',  label: 'OpenRouter',      desc: 'Multi-model gateway' },
    { id: 'lightning',   label: 'Lightning AI',    desc: 'OpenAI-compatible gateway' },
    { id: 'nvidia',      label: 'NVIDIA NIM',      desc: 'NVIDIA hosted models' },
    { id: 'deepseek',    label: 'DeepSeek',        desc: 'DeepSeek-V3 / R1' },
    { id: 'mistral',     label: 'Mistral AI',      desc: 'Mixtral, Mistral-Large' },
    { id: 'meta',        label: 'Meta (Llama)',    desc: 'Llama 3.x via API' },
    { id: 'ollama',      label: 'Ollama (local)',  desc: 'Local models, no API key' },
    { id: 'huggingface', label: 'HuggingFace',     desc: 'Download & run HF models via Ollama' },
];

export const PROVIDER_MODELS = {
    google:      ['gemini-2.0-flash', 'gemini-1.5-pro', 'gemini-1.5-flash'],
    cohere:      ['command-r-plus', 'command-r'],
    grok:        ['grok-2', 'grok-1'],
    perplexity:  ['llama-3.1-sonar-large-128k-online', 'llama-3.1-sonar-small-128k-online'],
    together:    ['meta-llama/Llama-3-70b-chat-hf', 'mistralai/Mixtral-8x7b-Instruct-v0.1'],
    cerebras:    ['llama3.1-70b', 'llama3.1-8b'],
    qwen:        ['qwen-max', 'qwen-plus', 'qwen-turbo'],
    glm:         ['glm-4', 'glm-4-flash'],
    groq:        ['qwen/qwen3-32b', 'llama-3.3-70b-versatile', 'mixtral-8x7b-32768', 'gemma2-9b-it'],
    openai:      ['gpt-4o', 'gpt-4o-mini', 'o1', 'o3-mini'],
    anthropic:   ['claude-sonnet-4-5', 'claude-opus-4', 'claude-haiku-4-5'],
    openrouter:  ['openai/gpt-4o', 'anthropic/claude-3-opus', 'meta-llama/llama-3-70b'],
    lightning:   [
        'openai/gpt-5', 'openai/gpt-5-mini', 'openai/o3',
        'anthropic/claude-sonnet-4-5-20250929',
        'lightning-ai/DeepSeek-V3.1', 'lightning-ai/llama-3.3-70b',
        'google/gemini-2.5-pro',
    ],
    nvidia:      ['meta/llama-3.1-70b-instruct', 'mistralai/mixtral-8x7b-instruct'],
    deepseek:    ['deepseek-chat', 'deepseek-reasoner'],
    mistral:     ['mistral-large-latest', 'mistral-medium', 'codestral-latest'],
    meta:        ['llama-3.3-70b', 'llama-3.1-405b'],
    ollama:      ['llama3', 'mistral', 'qwen2', 'gemma2', 'phi3', 'codellama'],
    huggingface: [],
};
